### ISSUE TITLE
Add sv_enableBounces

### ISSUE THREAD

**Issue by StickyStickx** [momo5502/boiii#163]
Would be cool to have bounces like all the other clients for when custom maps come out. For example I will be planning on making free run servers and it would be cool to have bounces enabled.

**Comment by diamante0018** [comment]
I was told by the guy behind the depatch tool that this is not possible on BO3 due to major differences between IW engine and 3arc.
Bounces will not work as the player is stopped at the end of the slope. If he could not do it it's safe to say it can't be done. although if someone as a breakthrough they are welcome to share their progress.

**Comment by Divity** [comment]
@diamante0018 its not impossible by any means. its also been achieved by him previously. https://www.youtube.com/watch?v=4EvMgWfVlIg
