### ISSUE TITLE
Stuck on an old network version?

### ISSUE THREAD

**Issue by notnightwolf** [momo5502/boiii#41]
After launching the game without "boiii" you wont be able to connect to the servers anymore, is there a way to fix this?
Stuck on network version 100.0.0.7.0.0

**Comment by momo5502** [comment]
This is not an issue with boiii. The reason this happens is because activision's content streaming servers are down.
You just haven't noticed, because the game caches the publisher files it downloads from those servers.
As boiii handles publisher files differently, it will invalidate the cache of the original game causing it to require a redownload of all files once you launch without boiii. This usually is not an issue, but as the servers are down, it is.

We are already aware of this and therefore implemented a workaround on our side by not invalidating the cache of the game anymore: https://github.com/momo5502/boiii/commit/ff63511349cc2ffd3dcace61533907359c2a9279
You likely just ran boiii before the workaround was in place.

However, there is no need to worry, you can still play the original game even if the servers are down. Just follow the steps in this tweet: https://twitter.com/shiversoftdev/status/1576160600127700992
