### ISSUE TITLE
Infinite loading screen when connecting to server

### ISSUE THREAD

**Issue by Spiiccyy** [momo5502/boiii#480]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 11 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. use this players file 
2. try to connect to any mp servers
3. boom infinite load

[players.zip](https://github.com/momo5502/boiii/files/11187727/players.zip)

### Expected Result

load infinitely 

### Actual Result

loaded infinitely 

### Severity/Priority

High/Critical

**Comment by momo5502** [comment]
Packet size limit is 0x4E8, which is quite arbitrary. So due to a big player info, the connect packet is too large and can not be sent. I tried compressing it as a quick fix, but the entropy is too high and the data therefore not really compressable.
I will have to recreate NET_SendPacket to increase the packet limit.

Will also check on the remote end if the buffers can hold that much data, but i think remote end is all safe and good.

**Comment by momo5502** [comment]
should be fixed by this: 5b27b3fc78ac46123b75ef127f8128303d1f54d1
