### ISSUE TITLE
Steam Error

### ISSUE THREAD

**Issue by vm10k** [momo5502/boiii#498]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit), SteamOS

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. ---------------------------
boiii.exe - Entry Point Not Found
---------------------------
The procedure entry point VProfInternalEnterScopeCurrentThread could not be located in the dynamic link library C:\Program Files (x86)\Steam\vstdlib_s64.dll. 
---------------------------
OK   
---------------------------

2. ---------------------------
boiii.exe - Entry Point Not Found
---------------------------
The procedure entry point ?ClaimMemory_Aligned@CValidator@@QEAAXPEBX@Z could not be located in the dynamic link library C:\Program Files (x86)\Steam\steamclient64.dll. 
---------------------------
OK   
---------------------------

3. 

### Severity/Priority

High/Critical

**Comment by linklel11** [comment]
Just wanted to put this out their. I've only ever run into this error when using a non-legal version of Black Ops 3. I will not tell you how I resolved this issue due to me not wanting to disrespect Momo's wishes of a certain site being taken down due to legal reasons and multiple useless issues being created. However if you are using a Legal copy of Black ops 3 I'm sure someone will come along and help you out.

**Comment by diamante0018** [comment]
Reinstall Steam. This is a problem on your PC.

**Comment by vm10k** [comment]
> 

i did re install steam multiple times it didnt work
