### ISSUE TITLE
Option To Disable Jetpack

### ISSUE THREAD

**Issue by amrurikaj** [momo5502/boiii#61]
Hi team,

This is only a suggestion (if possible) for option to disable Jetpack to make it more like boot on the ground cod.

**Comment by momo5502** [comment]
Pretty sure this can be done with a mod

**Comment by momo5502** [comment]
Yeah, I assumed so. I will close this issue, because the goal of this project is to provide a client, not specific mods. Such mods can be made with the existing mod tools of the game and published to the steam workshop. This client supports steam workshop content out of the box, so I don't see the need of creating that mod ourselves.

**Comment by amrurikaj** [comment]
@momo5502 yup.i saw someone already make the mod for boots on the ground. thanks man
