### ISSUE TITLE
Players joining are invisible and can't do anything.

### ISSUE THREAD

**Issue by certifiedbruhmoment** [momo5502/boiii#640]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. I start a zombies map, usually DE. No mods
2. My friends (2) join through /connect IP:27017, we are connected through Hamachi
3. My first friend joins fine on round 1, the second one always joins invisible, not on the scoreboard, can't interact with anything, and when revived, won't stand up.

### Expected Result

We all should join and be able to play normally after they respawn on round 2

### Actual Result

They join, the 1st one always join's fine, but the second one (in order of who connects first to my lobby) has a connection interrupted until the round ends, then he is invisible and can't interact with anything. 

### (Optional) Proof and Additional Information

I don't have a screenshot but I've seen this issue posted about on the discord, where people have posted screenshots.

### Severity/Priority

High/Critical

**Comment by JezuzLizard** [comment]
A dvar called zombies_minplayers was added to solve this problem in Plutonium T6 but became obsolete when lobbies were restored. A dvar with similar functionality could be added to boiii by patching Scr_GetNumExpectedPlayers() to return the value of zombies_minplayers. Doing this will cause the zombie scripts to wait until Scr_GetNumExpectedPlayers() is equal to Scr_GetNumConnectedPlayers() which should fix all hotjoin related issues as long as the players join during this period.

Since lobbies will not be restored as far as I'm aware this is a possible solution to patch this.

**Comment by certifiedbruhmoment** [comment]
can you describe how to do that by any chance a little more simply? i know plenty about computers but I've never had to do something like that before and it doesn't sound as simple as putting in a string into the console.

**Comment by diamante0018** [comment]
> 

I'll have a look at this I guess
