### ISSUE TITLE
Bots don't use certain streaks

### ISSUE THREAD

**Issue by Legend2579** [momo5502/boiii#746]
### Duplicate Issue Check

- [X] I have searched the list of issues on this repository. I confirm that this is not a duplicate of any open or closed issue(s).

### Your feature request or suggestion:

Unlocking Dark Matter and finishing the 100 Percenter challenge legitimately against bots alone is currently not possible due to a couple of roadblocks. The first is that the Chameleon camo for launchers is not possible to finish because bots do not call in any of the streaks required (Guardian/Hardened Sentry/Power Core). The second is that there are a lot of streaks that the bots don't use, that prevents certain anti-streak challenges from being completed, thus making 100 Percenter unobtainable. I've tested this in custom games by using the ban/protect system on streaks and raising the score multiplier to 5. 
Below is a list of streaks that bots will not use:

HC-XD
Care Package
Dart
Guardian
Lightning Strike
Hardened Sentry
Rolling Thunder
Wraith
Power Core
G.I. Unit
Mothership

Feature request and solution: Allow bots to use the streaks listed above

**Comment by diamante0018** [comment]
This is not worth our time. How about you play against real players too since there are so many playing our client?
There might technical limitations to why the bots can't use these kill streaks. Overcoming these limitations is currently of unknown difficulty to me and so I don't think this is a good feature request. I must assume it must be pretty dissatisfying too to grind challenges against AI.
