### ISSUE TITLE
Zm fastfile level not found (DLC zombie maps)

### ISSUE THREAD

**Issue by Dh5S** [momo5502/boiii#755]
### Bug Type

Client

### BOIII Version

v0.0.1 (Latest)

### Environment (Operating System)

Microsoft Windows 10 (64-Bit)

### Reproducibility Rate

High: The bug can (almost) always be reproduced

### Steps to Reproduce

1. Launch Boiii client and go to Zombies.
2. Join a Server or start a private - solo match with a DLC Map.

### Expected Result

DLC Maps in Zombies should run perfect, same as the DLC MP Maps.

### Actual Result

When loading in an Zombies game (DLC Map) i am getting a report which says, "Could not load fastfile for level 'zm_(Map name)' Could not read fastfile.

### (Optional) Proof and Additional Information

![Unbenannt](https://github.com/momo5502/boiii/assets/134172192/f0e12a81-0cbb-4841-aca9-68f95ac5f17d)

### Severity/Priority

High/Critical

**Comment by diamante0018** [comment]
Not a client issue.

**Comment by Dh5S** [comment]
> Not a client issue.

What is it then?

and how can i fix it

**Comment by CinderaceNamedEmber** [comment]
You can't play DLC you don't own.

Map's appearing "unlocked" are solely to avoid DLC owners getting locked out content they own since the client is in Early Access and therefore, proned to not work as intended - That's the legal-friendly way of putting it. 

Consider buying the DLC maps if you wish to play DLC maps.
If you can afford the £5/$6 to buy the client, you can afford to buy DE.

You could've saved time by asking in the Discord's **#help-client** channel.
