### ISSUE TITLE
Crash on Boot - Unable to import d3d11createdevice (d3d11.dll)

### ISSUE THREAD

**Issue by January-0002** [momo5502/boiii#84]
Hi Momo! Great work on the project so far :) Happy to see progress on it. 

Currently, with the latest EXE, I am personally having a bit of an issue. After compiling and getting the (yeah) boiii file, the game pops up this error.

![image](https://user-images.githubusercontent.com/39699418/204103673-4805a56c-e153-497c-ad59-0a05fcc4bd08.png)

Solutions attepmted: recompiling, reinstalling DirectX, reinstalling drivers via DDU, verifying game files.
Additionally I've noticed that someone else had a similar error and you recommended them to get rid of the old dx11 dll, which I have actually tried. Did not work.

**Comment by InSovietCS** [comment]
+UPDATE

In order to fix this issue, you need to specifically delete the BO3 EXE and let steam reacquire it. Then run the vanilla BO3 version until the in-game downloading of content is done. Once that is done, the (yeah) boiii version will run. Closing issue unless there's something to investigate.

**Comment by momo5502** [comment]
Just delete the leftover d3d11.dll
